name: Build and Publish CLI Toolbox Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'toolbox/Dockerfile'
   
jobs:
  build-and-publish:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./toolbox
          file: ./toolbox/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mp-toolbox:latest